export const ActionTypes = {
  SET_NOTES: "SET_NOTES",
  SET_FILTERED_NOTES: "SET_FILTERED_NOTES",
  SET_TITLE:"SET_TITLE",
  ADD_NEW_NOTE:"ADD_NEW_NOTE",
  LIST_VIEW:"LIST_VIEW",
  UPDATE_NOTE:"UPDATE_NOTE",
  SET_TRASH_NOTES:"SET_TRASH_NOTES",
  ADD_TRASH_NOTE:"ADD_TRASH_NOTE",
  REMOVE_TRASH_NOTE:"REMOVE_TRASH_NOTE",
  DELETE_NOTE:"DELETE_NOTE"
};